name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ $EC2_USER@$EC2_HOST:/path/to/deployment/directory/
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'cd /path/to/deployment/directory && ./deploy_script.sh'
